import {
    Biohazard,
    Bone,
    Church,
    Clock,
    CloudLightning,
    CloudMoon,
    Cpu,
    Cross,
    Crosshair,
    Crown,
    Droplet,
    Droplets,
    Eye,
    EyeOff,
    Flame,
    Ghost,
    Hand,
    HeartCrack,
    Leaf,
    Mountain,
    Orbit,
    PawPrint,
    Scale,
    Shapes,
    ShieldCheck,
    Skull,
    Sparkles,
    Star,
    Wand2,
    Waves,
    Wind,
    Zap,
} from "lucide-react";

// Une icône thématique par discipline (pas d'illustration dédiée comme pour
// les Clans : un simple pictogramme suffit ici, voir ClansIndexView pour le
// cas où une vraie image est nécessaire). Absente de cette table, une
// discipline retombe sur l'icône générique de la section (goutte).
const ICONS = {
    alienation: Hand,
    animalisme: PawPrint,
    auspex: Eye,
    celerite: Zap,
    chimerie: Wand2,
    daemonium: Skull,
    dissimulation: EyeOff,
    domination: Crown,
    "force-d-ame": ShieldCheck,
    harmonisation: Scale,
    obtenebration: CloudMoon,
    presence: Star,
    proteisme: Shapes,
    puissance: Flame,
    quietus: Crosshair,
    serpentis: Waves,
    temporis: Clock,
    vicissitude: Bone,
    "voie-de-l-attrait-des-flammes": Flame,
    "voie-de-l-eau": Droplets,
    "voie-de-l-emprisonnement-des-ames": Ghost,
    "voie-de-l-esprit": Ghost,
    "voie-de-la-conjuration": Sparkles,
    "voie-de-la-corruption": Biohazard,
    "voie-de-la-maitrise-elementaire": Orbit,
    "voie-de-la-puissance-de-neptune": Waves,
    "voie-de-la-technomancie": Cpu,
    "voie-de-la-terre": Mountain,
    "voie-de-mortis": Skull,
    "voie-des-cendres": Wind,
    "voie-des-ossements": Bone,
    "voie-du-cimetiere": Cross,
    "voie-du-controle-du-climat": CloudLightning,
    "voie-du-cosmos": Star,
    "voie-du-deuil": HeartCrack,
    "voie-du-feu": Flame,
    "voie-du-sang": Droplets,
    "voie-du-sepulcre": Church,
    "voie-du-vent": Wind,
    "voie-verte": Leaf,
};

export default function disciplineIcon(slug) {
    return ICONS[slug] || Droplet;
}
